<?php

namespace airmoi\FileMaker\Object;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 19:46:51.
 */
class FieldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Field
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Field;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getLayout
     * @todo   Implement testGetLayout().
     */
    public function testGetLayout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::isAutoEntered
     * @todo   Implement testIsAutoEntered().
     */
    public function testIsAutoEntered()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::isGlobal
     * @todo   Implement testIsGlobal().
     */
    public function testIsGlobal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getRepetitionCount
     * @todo   Implement testGetRepetitionCount().
     */
    public function testGetRepetitionCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getLocalValidationRules
     * @todo   Implement testGetLocalValidationRules().
     */
    public function testGetLocalValidationRules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getMaxCharacters
     * @todo   Implement testGetMaxCharacters().
     */
    public function testGetMaxCharacters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getValidationRules
     * @todo   Implement testGetValidationRules().
     */
    public function testGetValidationRules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getValidationMask
     * @todo   Implement testGetValidationMask().
     */
    public function testGetValidationMask()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::hasValidationRule
     * @todo   Implement testHasValidationRule().
     */
    public function testHasValidationRule()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::describeValidationRule
     * @todo   Implement testDescribeValidationRule().
     */
    public function testDescribeValidationRule()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::describeLocalValidationRules
     * @todo   Implement testDescribeLocalValidationRules().
     */
    public function testDescribeLocalValidationRules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::describeValidationRules
     * @todo   Implement testDescribeValidationRules().
     */
    public function testDescribeValidationRules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getResult
     * @todo   Implement testGetResult().
     */
    public function testGetResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getValueList
     * @todo   Implement testGetValueList().
     */
    public function testGetValueList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::getStyleType
     * @todo   Implement testGetStyleType().
     */
    public function testGetStyleType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::checkTimeStampFormatFourDigitYear
     * @todo   Implement testCheckTimeStampFormatFourDigitYear().
     */
    public function testCheckTimeStampFormatFourDigitYear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::checkTimeStampFormat
     * @todo   Implement testCheckTimeStampFormat().
     */
    public function testCheckTimeStampFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::checkDateFormat
     * @todo   Implement testCheckDateFormat().
     */
    public function testCheckDateFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::checkTimeFormat
     * @todo   Implement testCheckTimeFormat().
     */
    public function testCheckTimeFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::checkNumericOnly
     * @todo   Implement testCheckNumericOnly().
     */
    public function testCheckNumericOnly()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::checkDateValidity
     * @todo   Implement testCheckDateValidity().
     */
    public function testCheckDateValidity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Object\Field::checkTimeValidity
     * @todo   Implement testCheckTimeValidity().
     */
    public function testCheckTimeValidity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
