<?php

namespace airmoi\FileMaker;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 19:46:51.
 */
class FileMakerExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FileMakerException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FileMakerException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers airmoi\FileMaker\FileMakerException::getErrorString
     * @todo   Implement testGetErrorString().
     */
    public function testGetErrorString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\FileMakerException::isValidationError
     * @todo   Implement testIsValidationError().
     */
    public function testIsValidationError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
