<?php

namespace airmoi\FileMaker;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 20:40:06.
 */
class FileMakerValidationExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FileMakerValidationException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FileMakerValidationException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers airmoi\FileMaker\FileMakerValidationException::addError
     * @todo   Implement testAddError().
     */
    public function testAddError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\FileMakerValidationException::isValidationError
     * @todo   Implement testIsValidationError().
     */
    public function testIsValidationError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\FileMakerValidationException::numErrors
     * @todo   Implement testNumErrors().
     */
    public function testNumErrors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\FileMakerValidationException::getErrors
     * @todo   Implement testGetErrors().
     */
    public function testGetErrors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
