<?php

namespace airmoi\FileMaker\Parser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 19:46:51.
 */
class FMPXMLLAYOUTTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FMPXMLLAYOUT
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FMPXMLLAYOUT;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \airmoi\FileMaker\Parser\FMPXMLLAYOUT::parse
     * @todo   Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Parser\FMPXMLLAYOUT::setExtendedInfo
     * @todo   Implement testSetExtendedInfo().
     */
    public function testSetExtendedInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Parser\FMPXMLLAYOUT::_cdata
     * @todo   Implement test_cdata().
     */
    public function test_cdata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Parser\FMPXMLLAYOUT::associative_array_push
     * @todo   Implement testAssociative_array_push().
     */
    public function testAssociative_array_push()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
