<?php

namespace airmoi\FileMaker\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 20:40:04.
 */
class EditTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Edit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Edit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \airmoi\FileMaker\Command\Edit::execute
     * @todo   Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Command\Edit::setField
     * @todo   Implement testSetField().
     */
    public function testSetField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Command\Edit::setFieldFromTimestamp
     * @todo   Implement testSetFieldFromTimestamp().
     */
    public function testSetFieldFromTimestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Command\Edit::setModificationId
     * @todo   Implement testSetModificationId().
     */
    public function testSetModificationId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \airmoi\FileMaker\Command\Edit::setDeleteRelated
     * @todo   Implement testSetDeleteRelated().
     */
    public function testSetDeleteRelated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
