<?php

namespace airmoi\FileMaker\Object;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 19:46:50.
 */
class RelatedSetTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RelatedSet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RelatedSet;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers airmoi\FileMaker\Object\RelatedSet::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\RelatedSet::listFields
     * @todo   Implement testListFields().
     */
    public function testListFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\RelatedSet::getField
     * @todo   Implement testGetField().
     */
    public function testGetField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\RelatedSet::getFields
     * @todo   Implement testGetFields().
     */
    public function testGetFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\RelatedSet::loadExtendedInfo
     * @todo   Implement testLoadExtendedInfo().
     */
    public function testLoadExtendedInfo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
