<?php

namespace airmoi\FileMaker\Object;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 19:46:50.
 */
class ResultTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Result
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Result;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getLayout
     * @todo   Implement testGetLayout().
     */
    public function testGetLayout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getRecords
     * @todo   Implement testGetRecords().
     */
    public function testGetRecords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getFields
     * @todo   Implement testGetFields().
     */
    public function testGetFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getRelatedSets
     * @todo   Implement testGetRelatedSets().
     */
    public function testGetRelatedSets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getTableRecordCount
     * @todo   Implement testGetTableRecordCount().
     */
    public function testGetTableRecordCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getFoundSetCount
     * @todo   Implement testGetFoundSetCount().
     */
    public function testGetFoundSetCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getFetchCount
     * @todo   Implement testGetFetchCount().
     */
    public function testGetFetchCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getFirstRecord
     * @todo   Implement testGetFirstRecord().
     */
    public function testGetFirstRecord() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Object\Result::getLastRecord
     * @todo   Implement testGetLastRecord().
     */
    public function testGetLastRecord() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
