<?php

namespace airmoi\FileMaker\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 20:40:05.
 */
class AddTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Add
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Add;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers airmoi\FileMaker\Command\Add::execute
     * @todo   Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Add::setField
     * @todo   Implement testSetField().
     */
    public function testSetField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Add::setFieldFromTimestamp
     * @todo   Implement testSetFieldFromTimestamp().
     */
    public function testSetFieldFromTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
