<?php

namespace airmoi\FileMaker\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 20:40:05.
 */
class FindTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Find
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Find;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::addFindCriterion
     * @todo   Implement testAddFindCriterion().
     */
    public function testAddFindCriterion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::clearFindCriteria
     * @todo   Implement testClearFindCriteria().
     */
    public function testClearFindCriteria() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::addSortRule
     * @todo   Implement testAddSortRule().
     */
    public function testAddSortRule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::clearSortRules
     * @todo   Implement testClearSortRules().
     */
    public function testClearSortRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::execute
     * @todo   Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::setLogicalOperator
     * @todo   Implement testSetLogicalOperator().
     */
    public function testSetLogicalOperator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::setRange
     * @todo   Implement testSetRange().
     */
    public function testSetRange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::getRange
     * @todo   Implement testGetRange().
     */
    public function testGetRange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::setRelatedSetsFilters
     * @todo   Implement testSetRelatedSetsFilters().
     */
    public function testSetRelatedSetsFilters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\Find::getRelatedSetsFilters
     * @todo   Implement testGetRelatedSetsFilters().
     */
    public function testGetRelatedSetsFilters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
