<?php

namespace airmoi\FileMaker\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-09 at 20:40:06.
 */
class PerformScriptTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PerformScript
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PerformScript;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers airmoi\FileMaker\Command\PerformScript::setRange
     * @todo   Implement testSetRange().
     */
    public function testSetRange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\PerformScript::getRange
     * @todo   Implement testGetRange().
     */
    public function testGetRange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers airmoi\FileMaker\Command\PerformScript::execute
     * @todo   Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
